USE OLISTTECHDB;
GO

CREATE OR ALTER VIEW VW_TECHSUPPLYCHAIN AS
SELECT O.ORDER_ID AS ORDERID,
       CAST(O.ORDER_PURCHASE_TIMESTAMP AS DATETIME2) AS PURCHASEDATE,
       CAST(O.ORDER_DELIVERED_CUSTOMER_DATE AS DATETIME2) AS DELIVERYDATE,
       DATEDIFF(DAY, CAST(O.ORDER_PURCHASE_TIMESTAMP AS DATETIME), CAST(O.ORDER_DELIVERED_CUSTOMER_DATE AS DATETIME)) AS DAYSTODELIVER,
       P.PRODUCT_ID AS PRODUCTID,
       ISNULL(P.PRODUCT_CATEGORY_NAME, 'Unknown') AS CATEGORY,
       CAST(I.PRICE AS DECIMAL(10,2)) AS ITEMPRICE,
       CAST(I.FREIGHT_VALUE AS DECIMAL(10,2)) AS FREIGHTCOST,
       (CAST(I.PRICE AS DECIMAL(10,2)) + CAST(I.FREIGHT_VALUE AS DECIMAL(10,2))) AS TOTALLANDEDCOST
FROM RAW_ORDERS O
JOIN RAW_ORDERITEMS I 
ON O.ORDER_ID = I.ORDER_ID
JOIN RAW_PRODUCTS P 
ON I.PRODUCT_ID = P.PRODUCT_ID
WHERE UPPER(O.ORDER_STATUS) = 'DELIVERED'
AND UPPER(P.PRODUCT_CATEGORY_NAME) IN ('INFORMATICA_ACESSORIOS', 'TELEFONIA', 'ELETRONICOS', 'CONSOLES_GAMES');