CREATE DATABASE OLISTTECHDB;
GO
USE OLISTTECHDB;
GO

-- TABLE 1: PRODUCTS
CREATE TABLE RAW_PRODUCTS (
    PRODUCT_ID NVARCHAR(100),
    PRODUCT_CATEGORY_NAME NVARCHAR(100),
    PRODUCT_NAME_LENGHT NVARCHAR(50),
    PRODUCT_DESCRIPTION_LENGHT NVARCHAR(50),
    PRODUCT_PHOTOS_QTY NVARCHAR(50),
    PRODUCT_WEIGHT_G NVARCHAR(50),
    PRODUCT_LENGTH_CM NVARCHAR(50),
    PRODUCT_HEIGHT_CM NVARCHAR(50),
    PRODUCT_WIDTH_CM NVARCHAR(50)
);

-- TABLE 2: ORDERS
CREATE TABLE RAW_ORDERS (
    ORDER_ID NVARCHAR(100),
    CUSTOMER_ID NVARCHAR(100),
    ORDER_STATUS NVARCHAR(50),
    ORDER_PURCHASE_TIMESTAMP NVARCHAR(50),
    ORDER_APPROVED_AT NVARCHAR(50),
    ORDER_DELIVERED_CARRIER_DATE NVARCHAR(50),
    ORDER_DELIVERED_CUSTOMER_DATE NVARCHAR(50),
    ORDER_ESTIMATED_DELIVERY_DATE NVARCHAR(50)
);

-- TABLE 3: ORDER ITEMS
CREATE TABLE RAW_ORDERITEMS (
    ORDER_ID NVARCHAR(100),
    ORDER_ITEM_ID NVARCHAR(50),
    PRODUCT_ID NVARCHAR(100),
    SELLER_ID NVARCHAR(100),
    SHIPPING_LIMIT_DATE NVARCHAR(50),
    PRICE NVARCHAR(50),
    FREIGHT_VALUE NVARCHAR(50)
);